(prelude-require-package 'apache-mode)
(prelude-require-package 'helm-bibtex)
(prelude-require-package 'hyde)
(prelude-require-package 'linum-relative)
(prelude-require-package 'magit-gh-pulls)
(prelude-require-package 'magit-gerrit)
(prelude-require-package 'multiple-cursors)
(prelude-require-package 'mc-extras)
(prelude-require-package 'osx-clipboard)
(prelude-require-package 'osx-pseudo-daemon)

(require 'hyde)
(require 'linum-relative)
(require 'magit-gh-pulls)
(require 'magit-gerrit)
(require 'multiple-cursors)
(require 'mc-extras)
